// <auto-generated />
using DuAnStoreDT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DuAnStoreDT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230921131239_SeedDataAdminTable")]
    partial class SeedDataAdminTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DuAnStoreDT.Models.Admin", b =>
                {
                    b.Property<string>("useradmin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("passwordadmin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("useradmin");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            useradmin = "admin1",
                            passwordadmin = "admin1"
                        },
                        new
                        {
                            useradmin = "admin2",
                            passwordadmin = "admin2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
